### ISSUE TITLE
LayerToGeotiff/MultibandLayerToGeotiff invalid hdfs path

### ISSUE THREAD

**Issue by aklink** [biggis-project/biggis-landuse#15]
**Invalid hdfs path** issue in:
- [biggis.landuse.spark.examples.**LayerToGeotiff**](https://github.com/biggis-project/biggis-landuse/blob/master/src/main/scala/biggis/landuse/spark/examples/LayerToGeotiff.scala)
- [biggis.landuse.spark.examples.**MultibandLayerToGeotiff**](https://github.com/biggis-project/biggis-landuse/blob/master/src/main/scala/biggis/landuse/spark/examples/MultibandLayerToGeotiff.scala)

when exporting GeoTiff using hdfs path, e.g. 
- **hdfs://**/landuse-demo/landuse/out  ("**hdfs://**"  + "/landuse-demo/landuse/out")

then the path is falsely truncated to
- **hdfs:**/landuse-demo/landuse/out  ("**hdfs:**"  + "/landuse-demo/landuse/out")

by `GeoTiff.write(filename)` or `MultibandGeoFiff.write(filename)` , causing 
`java.io.FileNotFoundException: hdfs:/landuse-demo/landuse/out/result.tif (No such file or directory))`

Possible reason is that GeoTiff.write uses standard java.io to local filesystem. 

A similar issue reading/writing JSON files in hdfs could be solved by using
```
// Hadoop Config is accessible from SparkContext
implicit val fs : FileSystem = FileSystem.get(sc.hadoopConfiguration); 
```
and then replacing **java.io.FileWriter** by OutputStreamWriter with BufferedOutputStream and **fs.create**(**Path**(filename)):
- `val bw = new java.io.BufferedWriter(new java.io.FileWriter(new java.io.File(fileNameJson)))`

changed to:
- `val bw = new java.io.BufferedWriter(new java.io.OutputStreamWriter(new java.io.BufferedOutputStream(fs.create(new Path(fileNameJson)))))`

The problem is the java.io is hidden inside GeoTiff.write, which only accepts **String** as filename. There must be an alternative using org.apache.hadoop.fs in Geotrellis!

**Comment by aklink** [comment]
`package geotrellis.raster.io.geotiff.writer`
`object GeoTiffWriter {`
```
  def write(geoTiff: GeoTiffData, path: String): Unit = {
    val fos = new FileOutputStream(new File(path))
    try {
      val dos = new DataOutputStream(fos)
      try {
        new GeoTiffWriter(geoTiff, dos).write()
      } finally {
        dos.close
      }
    } finally {
      fos.close
    }
  }
```
Possible rework:
```
  def writeHdfs(geoTiff: GeoTiffData, path: Path)(implicit fs: FileSystem): Unit = {
    val fos = new java.io.BufferedOutputStream(fs.create(path))
    try {
      val dos = new java.io.DataOutputStream(fos)
      try {
        new GeoTiffWriter(geoTiff, dos).write()
      } finally {
        dos.close
      }
    } finally {
      fos.close
    }
  }
```

but: SparkException **not serializeable** when trying to build as standalone method (breaking GeoTiff / GeoTiffWriter relations)

**Comment by aklink** [comment]
Grigory
@pomadchin
12:49
hey
let me double check

yea, be sure that you have

`geotrellis.spark.io.hadoop._` in scope

and use one of these declarations:

```scala
def write(path: Path)(implicit sc: SparkContext): Unit
def write(path: Path, conf: Configuration): Unit
```

Tiffs, Pngs and Jpgs are supported types, implicits are here: https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/hadoop/Implicits.scala

but: still SparkException **not serializeable**

**Comment by pomadchin** [comment]
Hey! 
Try to use `def write(path: Path, conf: Configuration): Unit`, keep in mind that `SparkContext` and `Configuration` are not serializable, so use a serializable wrapper: 

```scala
import geotrellis.spark.io.hadoop._

val sc: SparkContext = ???
val conf = sc.hadoopConfiguration
val serConf = new SerializableConfiguration(conf) // it would ser fine

rdd.foreachPartition { partition =>
  partition.foreach(_.write(new Path("hdfs://..."), serConf.value))
}

```

**Comment by aklink** [comment]
> Grigory
> @pomadchin
> 14:20
> yeah, I answered you
> I’ll copy the answer here
> Try to use `def write(path: Path, conf: Configuration): Unit`, keep in mind that SparkContext and Configuration are not serializable, so use a serializable wrapper:
> 
> ```scala
> import geotrellis.spark.io.hadoop._
> 
> val sc: SparkContext = ???
> val conf = sc.hadoopConfiguration
> val serConf = new SerializableConfiguration(conf) // it would ser fine
> 
> rdd.foreachPartition { partition =>
>   partition.foreach { tuple => 
>     GeoTiff(tile, tileextent, crs)
>       .write(filename, serConf.value)
>   }
> }
> ```
> 

Implemented as:

```scala
    implicit val conf: Configuration = sc.hadoopConfiguration
    val serConf = new SerializableConfiguration(conf)

        outputRdd.foreachPartition { partition =>
          partition.foreach { tuple =>
            val (key, tile) = tuple
            val (col, row) = (key.col, key.row)
            val tileextent: Extent = metadata.layout.mapTransform(key)
            val filename = new Path(outputPath + "_" + col + "_" + row + ".tif")
            logger info s" writing: '${filename.toString}'"
            GeoTiff(tile, tileextent, crs)
              .write(filename, serConf.value)
          }
        }
```

But causing exception:

`org.apache.avro.AvroTypeException: Found geotrellis.raster.ArrayMultibandTile, expecting union. This can be caused by using a type parameter which doesn't match the object being deserialized.`

Attention: the "old" code (without serialized hadoopConfiguration) seems to be causing same issue now, too, there must be an external cause of this issue!

**Comment by pomadchin** [comment]
Yep, looks like smth is corrupted in the `outputRdd`

**Comment by aklink** [comment]
**Finally working.** 
The geotrellis-catalog was corrupted in hdfs during testing, causing invalid outputRdd resulting in a org.apache.avro.AvroTypeException. I had to reimport all DOP and Sentinel2 scenes.
Some code cleanup will be needed afterwards, and move working code to api later.

@pomadchin: Thank you very much! You have been a great help to track down and solve the issue! I really appreciate your support!
