### ISSUE TITLE
TODO: Convert shapefile to raster

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-landuse#4]
- using spark
- as a new layer (needs resolution parameter)
- as a new band

**Comment by aklink** [comment]
[Rasterize RDD[Geometries] to RDD[Tile] #2228](https://github.com/locationtech/geotrellis/issues/2228)

[RasterizeRDD for Geometry #2266](https://github.com/locationtech/geotrellis/pull/2266)

**Comment by aklink** [comment]
https://github.com/echeipesh/geotrellis/pull/10

https://github.com/echeipesh/geotrellis/pull/10/commits/007309c0c47db0dcddb499bdc32609c62275dc9c

**Comment by vsimko** [comment]
fixed in commit 292ddb841853880ade3b8264c5d679afb2e1eb31
